# Generated by Django 4.0.4 on 2022-06-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_like_likepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=128),
        ),
    ]
